### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [devXprite/star-weather#12]
Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under gssoc24-ext, and hacktoberfest-accepted.

**Comment by devXprite** [comment]
Hey, thanks for the suggestion! At the moment, we don't really need something like this. It might actually have a negative impact on the user experience, so I’m going to close this one for now. However, I appreciate your input!
