### ISSUE TITLE
Create a footer section

### ISSUE THREAD

**Issue by anushkajjadhav** [devXprite/star-weather#13]
I can add a footer with all social media links of the site and contact information

**Comment by ShreyaSnehal** [comment]
Please assign me this task and add the label of gssoc-ext , hacktoberfest-accepted, hacktoberfest.

**Comment by devXprite** [comment]
> I can add a footer with all social media links of the site and contact information

Hey, thanks for the suggestion! Currently, we have a very minimal footer, and we’re not looking to add social media links or contact information at the moment. I am closing this issue, but I appreciate your input!
