### ISSUE TITLE
Add Dark/Light Theme Toggle and Scroll-to-Top Button

### ISSUE THREAD

**Issue by manu-hn** [devXprite/star-weather#17]
Hi @devXprite 
I'd like to propose adding two new features:

A dark/light theme toggle to enhance user experience and accessibility.
A scroll-to-top button at the bottom of the page for smoother navigation.
 Please assign this issue to me and kindly add the labels gssoc-extd, hacktoberfest, and any other suitable labels.

**Comment by devXprite** [comment]
Hey, thanks for the suggestion but It looks like both features are duplicates of issues #2  and  #10. So I'm closing this one,
