### ISSUE TITLE
[Feature Request]: A Chatbot which guides user according to need

### ISSUE THREAD

**Issue by Peart-Guy** [devXprite/star-weather#19]
The chatbot will have a feature of Natural Language which will easily omit user's grammatical mistakes and spelling mistakes in chat input. The admin can train the chatbot whenever needed in a .json file.

-->The chatbot will have its back end in Python with modules like PyTorch, NumPy, etc. and and a basic front end in CSS and JS and HTML
 
I would like to work on this issue
Name: Ankan
Participant Role: Contributor , GSSOC-24 Extd

**Comment by devXprite** [comment]
Hey, thanks for the suggestion but at this point, it’s not something we need, so I’m going to close this issue.
