### ISSUE TITLE
add animations using gsap

### ISSUE THREAD

**Issue by priyashuu** [devXprite/star-weather#28]
Feature Description
Objective: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

Use Case
Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback!

**Comment by 0xSaksham** [comment]
Try to add a text-animation and create a PR and I'll take a look into it
