### ISSUE TITLE
Implementing Hover functionality

### ISSUE THREAD

**Issue by Monu2114** [devXprite/star-weather#4]
Better ui experience by implementing hover over the components . Pls assign me this task.  under gssoc ext level and hacktoberfest acceptance

**Comment by Devanshu1603** [comment]
i want to work on this issue .can you please assign it to me under gssoc ext level.

**Comment by Ibrangrd** [comment]
I have use so many hover effect so , can do it better . So, can you assign to me ?

**Comment by devXprite** [comment]
> Better ui experience by implementing hover over the components . Pls assign me this task. under gssoc ext level and hacktoberfest acceptance

Hey! @Monu2114  I've assigned you to the issue.

**Comment by Monu2114** [comment]
Thanks will work on this issue soon

**Comment by Monu2114** [comment]
@devXprite hey am working on this issue now but can u assign labels gssoc24-extd, level2 and hacktoberfest-accepted labels to this issue ?
