### ISSUE TITLE
Adding logo and navbar

### ISSUE THREAD

**Issue by anshika-1102** [devXprite/star-weather#6]
- I want to make a logo for the website
- I want to make a navbar including various sections for the same.
- If you want I can make the 'About Us' and 'Our Services' section page too for the website.

**Comment by Divyansh2992** [comment]
i want to contribute.

**Comment by chetanck03** [comment]
Hi , can I contribute something..?

**Comment by hiimanshu12** [comment]
Hello, I want to contribute .
